pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "status-success=ci/circleci: build"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
        strict: true
