name: automerge
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: trilom/file-changes-action@v1.2.3
        id: changes
        with:
          githubToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'


