name: automerge
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            README:
              - 'README.md'
      - name: automerge
        uses: ridedott/merge-me-action@v2
        env:
          GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        if: steps.changes.outputs.README == 'true'