name: CI
on:
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v5
      - run: sbt -v lint
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
#  test:
#    strategy:
#      fail-fast: false
#      matrix:
#        jdk: [ adopt@1.8 ] # , adopt@1.11, adopt@1.14 ]
#        scala: [ 2.13.5 ] # , 2.12.13, 2.11.12 ]
#    runs-on: ubuntu-latest
#    needs: lint
#    env:
#      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
#      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
#      AWS_REGION: ap-northeast-1
#      TEST_TIME_FACTOR: 3
#    steps:
#      - uses: actions/checkout@v2.3.4
#        with:
#          fetch-depth: 0
#      - uses: olafurpg/setup-scala@v10
#        with:
#          java-version: ${{ matrix.jdk }}
#      - uses: coursier/cache-action@v5
#      - uses: olafurpg/setup-gpg@v3
#      - run: sbt -v ++${{ matrix.scala }} test
#      - name: clean up
#        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: trilom/file-changes-action@v1.2.3
        id: file_changes
        with:
          githubToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - id: update-flag
        run: |
          if echo '${{ steps.file_changes.outputs.files }}' | grep -q 'README.md'; then
            echo "::set-output name=update::true"
          else
            echo "::set-output name=update::false"
          fi
      - name: automerge
        uses: ridedott/merge-me-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.update-flag.outputs.update == 'true'